version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: grpc_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: go_test_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  grpc-server:
    build: .
    container_name: grpc_server
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: root
      DB_NAME: go_test_db
    ports:
      - "50051:50051"
    restart: on-failure

volumes:
  pgdata:
